modules:
-   description: Block Storage API Product Documentation
    name: block-storage
    path: block-storage.openapi.yaml
    summary: Block Storage API Product Documentation
    super_internal: false
    url: https://block-storage.jaxyendy.com/openapi.json
    version: v1
-   description: DBaaS API Product.
    name: dbaas
    path: dbaas.openapi.yaml
    summary: DBaaS API Product.
    super_internal: false
    url: https://dbaas.jaxyendy.com/openapi.json
    version: 1.20.0
-   description: APIs related to the Kubernetes product.
    name: kubernetes
    path: kubernetes.openapi.yaml
    summary: APIs related to the Kubernetes product.
    super_internal: false
    url: https://mke.br-ne-1.com/docs/openapi-with-snippets.json
    version: 0.1.0
-   description: APIs referentes ao produto de VPC
    name: network
    path: network.openapi.yaml
    summary: APIs referentes ao produto de VPC
    super_internal: false
    url: https://network.jaxyendy.com/openapi.json
    version: 1.124.1
-   description: Virtual Machine Api Product
    name: virtual-machine-xaas
    path: virtual-machine-xaas.openapi.yaml
    summary: Virtual Machine Api Product
    super_internal: true
    url: https://virtual-machine.jaxyendy.com/internal/v1/openapi.json
    version: 1.232.0
-   description: Virtual Machine Api Product
    name: virtual-machine
    path: virtual-machine.openapi.yaml
    summary: Virtual Machine Api Product
    super_internal: false
    url: https://virtual-machine.jaxyendy.com/openapi.json
    version: v1
version: 1.0.0
