name: Internal Release

on:
  workflow_dispatch:

concurrency:
  group: ci-check-${{ github.ref }}
  
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Run GoReleaser
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2
          args: release --clean --config="goreleaser_internal.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT2 }}
          PRIVATE_KEY_PATH: ${{ secrets.SSH_ID_RSA_MAGALUCLI }}
